import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../../scss/global.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ['400', '500', '700','800', '900'],
  display: 'swap', 
});

export const metadata: Metadata = {
  title: "Anyboost",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="wrapper">
          <Header />
            {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
